[package]
name = "colink-playbook"
version = "0.0.1"
edition = "2021"

[dependencies]
colink = "0.3.7"
tokio = "1.24"
tracing = "0.1"
toml = "0.4.5"
regex = "1.5.4"
rust-crypto = "0.2.36"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }