on:
    push:
      branches:
        - main
    pull_request:
  
name: check

jobs:
    check:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            components: rustfmt, clippy
        - name: Checkskip check in macos because it is slow
          run: cargo check --release
        - name: Build
          run: cargo build --all-targets
        - name: Format check
          run: cargo fmt --all -- --check
        - name: Clippy test
          run: cargo clippy --profile test -- -D warnings -D clippy::dbg_macro